import { Language, View } from './types';

export const TRANSLATIONS = {
  [Language.EN]: {
    'app.title': 'Office Tools Hub',
    'nav.dashboard': 'Dashboard',
    'nav.qr': 'QR Generator',
    'nav.pdf': 'Compress PDF',
    'nav.pdf_merge': 'Merge PDF',
    'nav.pdf_split': 'Split PDF',
    'nav.pdf_watermark': 'Watermark PDF',
    'nav.image': 'Compress Image',
    'nav.url': 'URL Shortener',
    'dashboard.welcome': 'Welcome back!',
    'dashboard.search': 'Search tools...',
    'dashboard.recent': 'Recent Activity',
    'dashboard.noRecent': 'No recent tools used.',
    'qr.label': 'Text or URL',
    'qr.generate': 'Generate QR',
    'qr.download': 'Download PNG',
    'qr.options': 'Options',
    'qr.logo': 'Logo (Optional)',
    'qr.upload': 'Upload Logo',
    'qr.size': 'Logo Size',
    'qr.showText': 'Show Text below QR',
    'pdf.drop': 'Drag & Drop PDF here',
    'pdf.optimize': 'Compress PDF',
    'pdf.processing': 'Processing page',
    'pdf.settings': 'Compression Settings',
    'pdf.quality': 'Image Quality',
    'pdf.resolution': 'Resolution (DPI)',
    'pdf.res_low': 'Low (72 DPI) - Screen',
    'pdf.res_med': 'Medium (150 DPI) - E-book',
    'pdf.res_high': 'High (300 DPI) - Print',
    'pdf.warning': 'This method converts pages to images to maximize compression. Text will no longer be selectable.',
    'pdf.estimating': 'Estimating size...',
    'pdf.estimated_size': 'Est. Size: ~',
    'pdf_merge.drop': 'Drop PDF files here',
    'pdf_merge.add': 'Add PDFs',
    'pdf_merge.list': 'Files to Merge',
    'pdf_merge.action': 'Merge PDFs',
    'pdf_merge.empty': 'No files selected yet.',
    'pdf_merge.hint': 'Use arrows to reorder files before merging.',
    'pdf_split.drop': 'Drop PDF file to split',
    'pdf_split.pages': 'pages',
    'pdf_split.mode_custom': 'Custom Selection',
    'pdf_split.mode_fixed': 'Fixed Range',
    'pdf_split.select_hint': 'Click pages to keep or use range below',
    'pdf_split.range_label': 'Select Range (e.g. 1-5, 8)',
    'pdf_split.fixed_label': 'Split every X pages:',
    'pdf_split.fixed_hint': 'Document will be split into chunks of this size.',
    'pdf_split.output_label': 'Output Mode:',
    'pdf_split.output_single': 'Merge selected into one PDF',
    'pdf_split.output_zip': 'Extract as separate PDFs (ZIP)',
    'pdf_split.select_all': 'Select All',
    'pdf_split.deselect_all': 'Deselect All',
    'pdf_split.action': 'Process PDF',
    'pdf_split.action_zip': 'Download ZIP',
    'pdf_split.empty_selection': 'Select at least one page',
    'wm.tab_text': 'Place Text',
    'wm.tab_image': 'Place Image',
    'wm.text_label': 'Watermark Text',
    'wm.format': 'Format',
    'wm.position': 'Position',
    'wm.transparency': 'Transparency',
    'wm.rotation': 'Rotation',
    'wm.action': 'Add Watermark',
    'image.drop': 'Drag & Drop Image (JPG, PNG, WebP)',
    'image.quality': 'Quality',
    'image.compress': 'Compress',
    'image.download': 'Download',
    'url.mode.mock': 'Mock Mode',
    'url.mode.api': 'API Mode',
    'url.domain': 'Domain',
    'url.placeholder': 'https://example.com/very/long/url',
    'url.shorten': 'Shorten',
    'url.history': 'History',
    'common.delete': 'Delete',
    'common.copy': 'Copy',
    'common.copied': 'Copied!',
    'common.back': 'Back',
  },
  [Language.ID]: {
    'app.title': 'Hub Alat Kantor',
    'nav.dashboard': 'Dasbor',
    'nav.qr': 'Generator QR',
    'nav.pdf': 'Kompres PDF',
    'nav.pdf_merge': 'Gabung PDF',
    'nav.pdf_split': 'Pisah PDF',
    'nav.pdf_watermark': 'Watermark PDF',
    'nav.image': 'Kompres Gambar',
    'nav.url': 'Penyingkat URL',
    'dashboard.welcome': 'Selamat datang kembali!',
    'dashboard.search': 'Cari alat...',
    'dashboard.recent': 'Aktivitas Terkini',
    'dashboard.noRecent': 'Belum ada alat yang digunakan.',
    'qr.label': 'Teks atau URL',
    'qr.generate': 'Buat QR',
    'qr.download': 'Unduh PNG',
    'qr.options': 'Opsi',
    'qr.logo': 'Logo (Opsional)',
    'qr.upload': 'Unggah Logo',
    'qr.size': 'Ukuran Logo',
    'qr.showText': 'Tampilkan Teks di bawah QR',
    'pdf.drop': 'Tarik & Taruh PDF di sini',
    'pdf.optimize': 'Kompres PDF',
    'pdf.processing': 'Memproses halaman',
    'pdf.settings': 'Pengaturan Kompresi',
    'pdf.quality': 'Kualitas Gambar',
    'pdf.resolution': 'Resolusi (DPI)',
    'pdf.res_low': 'Rendah (72 DPI) - Layar',
    'pdf.res_med': 'Sedang (150 DPI) - E-book',
    'pdf.res_high': 'Tinggi (300 DPI) - Cetak',
    'pdf.warning': 'Metode ini mengubah halaman menjadi gambar untuk kompresi maksimal. Teks tidak akan bisa disalin lagi.',
    'pdf.estimating': 'Menghitung estimasi...',
    'pdf.estimated_size': 'Est. Ukuran: ~',
    'pdf_merge.drop': 'Taruh file PDF di sini',
    'pdf_merge.add': 'Tambah PDF',
    'pdf_merge.list': 'File yang akan digabung',
    'pdf_merge.action': 'Gabungkan PDF',
    'pdf_merge.empty': 'Belum ada file dipilih.',
    'pdf_merge.hint': 'Gunakan panah untuk mengurutkan file sebelum digabung.',
    'pdf_split.drop': 'Taruh file PDF untuk dipisah',
    'pdf_split.pages': 'halaman',
    'pdf_split.mode_custom': 'Pilihan Manual',
    'pdf_split.mode_fixed': 'Rentang Tetap',
    'pdf_split.select_hint': 'Klik halaman untuk memilih atau gunakan rentang',
    'pdf_split.range_label': 'Pilih Rentang (cth: 1-5, 8)',
    'pdf_split.fixed_label': 'Pisah setiap X halaman:',
    'pdf_split.fixed_hint': 'Dokumen akan dipecah menjadi bagian-bagian sebesar ini.',
    'pdf_split.output_label': 'Mode Output:',
    'pdf_split.output_single': 'Gabung jadi 1 PDF',
    'pdf_split.output_zip': 'Pisah jadi banyak file (ZIP)',
    'pdf_split.select_all': 'Pilih Semua',
    'pdf_split.deselect_all': 'Hapus Pilihan',
    'pdf_split.action': 'Proses PDF',
    'pdf_split.action_zip': 'Unduh ZIP',
    'pdf_split.empty_selection': 'Pilih minimal satu halaman',
    'wm.tab_text': 'Teks',
    'wm.tab_image': 'Gambar',
    'wm.text_label': 'Teks Watermark',
    'wm.format': 'Format Teks',
    'wm.position': 'Posisi',
    'wm.transparency': 'Transparansi',
    'wm.rotation': 'Rotasi',
    'wm.action': 'Tambahkan Watermark',
    'image.drop': 'Tarik & Taruh Gambar (JPG, PNG, WebP)',
    'image.quality': 'Kualitas',
    'image.compress': 'Kompres',
    'image.download': 'Unduh',
    'url.mode.mock': 'Mode Mock',
    'url.mode.api': 'Mode API',
    'url.domain': 'Domain',
    'url.placeholder': 'https://contoh.com/url/yang/panjang',
    'url.shorten': 'Singkat',
    'url.history': 'Riwayat',
    'common.delete': 'Hapus',
    'common.copy': 'Salin',
    'common.copied': 'Disalin!',
    'common.back': 'Kembali',
  },
};

export const TOOLS_CONFIG = [
  { id: View.QR_CODE, icon: 'QrCode', color: 'text-purple-500', bg: 'bg-purple-100 dark:bg-purple-900/30' },
  { id: View.PDF_COMPRESS, icon: 'FileDown', color: 'text-red-500', bg: 'bg-red-100 dark:bg-red-900/30' },
  { id: View.PDF_MERGE, icon: 'Files', color: 'text-orange-500', bg: 'bg-orange-100 dark:bg-orange-900/30' },
  { id: View.PDF_SPLIT, icon: 'Scissors', color: 'text-pink-500', bg: 'bg-pink-100 dark:bg-pink-900/30' },
  { id: View.PDF_WATERMARK, icon: 'Stamp', color: 'text-indigo-500', bg: 'bg-indigo-100 dark:bg-indigo-900/30' },
  { id: View.IMAGE_COMPRESS, icon: 'Image', color: 'text-green-500', bg: 'bg-green-100 dark:bg-green-900/30' },
  { id: View.URL_SHORTENER, icon: 'Link', color: 'text-blue-500', bg: 'bg-blue-100 dark:bg-blue-900/30' },
];